apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: system
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
data:
  config.yaml: |
    api:
      server:
        url: "http://lissto-api:8080"
    logging:
      level: info
    namespaces:
      global: "lissto-global"
      developerPrefix: "dev-"
    repos:
      main:
        url: "https://github.com/example/repo"
        name: "Main Repository"
        branches:
          - main
          - master
    stacks:
      ingress:
        internal:
          ingressClass: "nginx"
          hostSuffix: ".internal.example.com"
          tlsSecret: "wildcard-internal-tls"

