apiVersion: env.lissto.dev/v1alpha1
kind: Blueprint
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: blueprint-sample
spec:
  # TODO(user): Add fields here
