api:
  server:
    url: "http://lissto-api:8080"

logging:
  level: "info"

namespaces:
  global: "lissto-global"
  developerPrefix: "dev-"

repos:
  main:
    url: "https://github.com/example/repo"
    name: "Main Repository"
    branches: ["main", "master"]

stacks:
  images:
    registry: "123.ecr.aws.amazon.com"
    repositoryPrefix: "lissto-dev/"
  ingress:
    internal:
      ingressClass: "haproxy"
      hostSuffix: ".dev.lissto.dev"
      tlsSecret: "wildcard-tls"
    internet:
      ingressClass: "haproxy-public"
      hostSuffix: ".dev-public.lissto.dev"
      tlsSecret: "wildcard-internet-tls"

# Stack suspension configuration
stack:
  defaultSuspendTimeout: 5m
