api:
  server:
    url: "http://lissto-api:8080"

logging:
  level: "info"

namespaces:
  global: "lissto-global"
  developerPrefix: "dev-"
  autoCreatePrefix: true

repos:
  main:
    url: "https://github.com/example/repo"
    name: "Main Repository"
    branches: ["main", "master"]

stacks:
  global:
    images:
      registry: "123.ecr.aws.amazon.com"
      repositoryPrefix: "lissto-dev/"
  public:
    ingressClass: "haproxy"
    hostSuffix: ".dev.lissto.dev"
